version = 0.1

[default.deploy.parameters]
stack_name = "hello-world-sam-ptest"
region = "ap-south-1"
s3_bucket = "sameed-imp-eng"
s3_prefix = "hello-world-sam/ptest"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=ptest"
confirm_changeset = false
fail_on_empty_changeset = false
