AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple SAM app deployed through Harness CD

Parameters:
  Environment:
    Type: String
    Default: ptest

Globals:
  Function:
    Runtime: python3.10
    Timeout: 30
    MemorySize: 256

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "hello-world-${Environment}"
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
